# Generated by Django 4.2.8 on 2024-01-09 22:54

import api.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Wrapped',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(default=api.models.generate_unique_code, max_length=8, unique=True)),
                ('host', models.CharField(max_length=50, unique=True)),
                ('name', models.CharField(max_length=64)),
                ('file', models.FileField(upload_to='watch_history/jsons/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('count', models.IntegerField(default=0)),
                ('time', models.IntegerField(default=0)),
                ('channels', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video_id', models.CharField(max_length=100)),
                ('title', models.CharField(max_length=100)),
                ('channel', models.CharField(max_length=100)),
                ('duration', models.CharField(max_length=64)),
                ('category', models.CharField(max_length=100)),
                ('thumbnail', models.CharField(max_length=100)),
                ('month', models.IntegerField(default=0)),
                ('date', models.DateTimeField()),
                ('views', models.IntegerField(default=0)),
                ('wrap', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='videos', to='api.wrapped')),
            ],
        ),
    ]
