# Generated by Django 4.2.8 on 2023-12-19 22:06

import api.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Wrapped',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(default=api.models.generate_unique_code, max_length=8, unique=True)),
                ('host', models.CharField(max_length=50, unique=True)),
                ('name', models.CharField(max_length=64)),
                ('file', models.FileField(upload_to='watch_history/jsons/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
