# Generated by Django 4.2.8 on 2024-01-05 23:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Analysis',
        ),
        migrations.RemoveField(
            model_name='wrapped',
            name='music_count',
        ),
        migrations.DeleteModel(
            name='Month',
        ),
    ]
