# Generated by Django 4.2.8 on 2023-12-21 22:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='wrapped',
            name='count',
            field=models.IntegerField(default=0),
        ),
    ]
