# Generated by Django 5.0.1 on 2024-01-13 04:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_video_views'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wrapped',
            name='file',
            field=models.FileField(upload_to=''),
        ),
    ]
