# Generated by Django 4.2.8 on 2024-01-08 23:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_delete_analysis_remove_wrapped_music_count_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='wrapped',
            name='channels',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='wrapped',
            name='time',
            field=models.IntegerField(default=0),
        ),
    ]
