# Generated by Django 4.2.8 on 2023-12-31 08:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_wrapped_count'),
    ]

    operations = [
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('channel', models.CharField(max_length=100)),
                ('duration', models.CharField(max_length=64)),
                ('category', models.CharField(max_length=100)),
                ('thumbnail', models.CharField(max_length=100)),
                ('wrap', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='videos', to='api.wrapped')),
            ],
        ),
    ]
