# Generated by Django 4.2.8 on 2024-01-09 02:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_wrapped_channels_wrapped_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='month',
            field=models.IntegerField(default=0),
        ),
    ]
