# Generated by Django 4.2.8 on 2024-01-01 02:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_video'),
    ]

    operations = [
        migrations.AddField(
            model_name='wrapped',
            name='music_count',
            field=models.IntegerField(default=0),
        ),
    ]
