# Generated by Django 5.0 on 2024-01-31 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_video_watched'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wrapped',
            name='filename',
            field=models.CharField(default=None, max_length=100, null=True),
        ),
    ]
