# Generated by Django 5.0 on 2024-01-31 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_alter_wrapped_filename'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='duration',
            field=models.BigIntegerField(default=0),
        ),
    ]
